name: particular-platform-masstransit-recoverability-rabbit

services:
  rabbitmq:
    profiles: ['', infrastructure]
    container_name: "rabbitmq"
    image: rabbitmq:management-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RabbitMQ__Host=rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    ports:
      - 33721:5672
      - 33672:15672     
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins

  service-control:
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - LICENSINGCOMPONENT_RABBITMQ_APIURL=${RABBITMQ_MANAGEMENT_API_URL}
      - LICENSINGCOMPONENT_RABBITMQ_USERNAME=${RABBITMQ_MANAGEMENT_API_USERNAME}
      - LICENSINGCOMPONENT_RABBITMQ_PASSWORD=${RABBITMQ_MANAGEMENT_API_PASSWORD}

  masstransit-connector:
    environment:
      - RABBITMQ_MANAGEMENT_API_URL
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
  
  clientui:
    environment:
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_VIRTUALHOST
  sales:
    environment:
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_VIRTUALHOST
  shipping:
    environment:
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_VIRTUALHOST
  billing:
    environment:
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_VIRTUALHOST

configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_shovel_management]."

volumes:
  rabbitmq-data:
  rabbitmq-logs: