services:
  masstransit-connector:
    environment:
      - RABBITMQ_MANAGEMENT_API_URL
      - RABBITMQ_MANAGEMENT_API_USERNAME
      - RABBITMQ_MANAGEMENT_API_PASSWORD
  service-control:
    environment:
      - LICENSINGCOMPONENT_RABBITMQ_APIURL=${RABBITMQ_MANAGEMENT_API_URL}
      - LICENSINGCOMPONENT_RABBITMQ_USERNAME=${RABBITMQ_MANAGEMENT_API_USERNAME}
      - LICENSINGCOMPONENT_RABBITMQ_PASSWORD=${RABBITMQ_MANAGEMENT_API_PASSWORD}