name: particular-platform-masstransit-recoverability
x-transport: &transport-env
  environment:
    RAVENDB_CONNECTIONSTRING: "http://servicecontrol-db:8080"
    ALLOWMESSAGEEDITING: true
    SHOW_PENDING_RETRY: true
    TRANSPORTTYPE: "RabbitMQ.QuorumConventionalRouting"
    CONNECTIONSTRING: "host=rabbitmq"
    MANAGEMENTAPI: "http://guest:guest@rabbitmq:15672"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics is_running | grep "is fully booted and running"
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    ports:
      - 15672:15672
      - 56721:5672
  service-control-db:
    profiles: [platform]
    container_name: servicecontrol-db
    image: particular/servicecontrol-ravendb:6
    volumes:
      - sc-data:/var/lib/ravendb/data
  service-control:
    profiles: [platform]
    depends_on:
      service-control-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    container_name: servicecontrol
    image: particular/servicecontrol:6
    command: "--setup-and-run"
    ports:
      - 33333:33333
    << : [*transport-env]
  masstransit-connector:
    profiles: [platform]
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: masstransit-connector
    image: particular/servicecontrol-connector-masstransit:latest
    #image: servicecontrol-connector-masstransit:8.0
    command: "--setup-and-run"
    << : [*transport-env]
  service-pulse:
    profiles: [platform]
    depends_on:
      - service-control
    container_name: servicepulse
    image: particular/servicepulse:latest
    ports:
        - 9090:9090
    environment:
        - SERVICECONTROL_URL=http://localhost:33333/api/
        - ENABLE_REVERSE_PROXY=false
        - SHOW_PENDING_RETRY=true
        - ALLOW_MESSAGE_EDITING=true

configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_shovel_management]."

volumes:
  sc-data:
  rabbitmq-data:
  rabbitmq-logs: