services:
  service-control-db:
    container_name: servicecontrol-db
    image: particular/servicecontrol-ravendb:latest
    volumes:
      - sc-data:/var/lib/ravendb/data
  service-control:
    depends_on:
      service-control-db:
        condition: service_healthy
    container_name: servicecontrol
    image: particular/servicecontrol:latest
    command: "--setup-and-run"
    ports:
      - 33333:33333
    environment:
      - TRANSPORTTYPE
      - CONNECTIONSTRING=${CONNECTION_STRING}
      - RAVENDB_CONNECTIONSTRING=http://servicecontrol-db:8080
      - ALLOWMESSAGEEDITING=true
      - SHOW_PENDING_RETRY=true
  masstransit-connector:
    depends_on:
      service-control:
        condition: service_healthy
    container_name: masstransit-connector
    image:  particular/servicecontrol-masstransit-connector:0.1.0-alpha.6
    volumes:
      - ./queues.txt:/app/queues.txt:ro
    environment:
      - TRANSPORT_TYPE
      - CONNECTION_STRING
  service-pulse:
    depends_on:
      service-control:
        condition: service_healthy
    container_name: servicepulse
    image: particular/servicepulse:latest
    ports:
        - 9090:9090
    environment:
        SERVICECONTROL_URL: http://servicecontrol:33333/api/
        ENABLE_REVERSE_PROXY: false
        SHOW_PENDING_RETRY: false
  frontend:
    container_name: frontend
    build:
      context: ./frontend  # Path to the folder containing Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - billing
      - shipping
      - sales
      - clientui
    volumes:
      - ./frontend:/app  # Optional for hot reloading
    environment:
      - BILLING_SIGNALR=billing:5002
      - CLIENT_SIGNALR=clientui:5000
      - SALES_SIGNALR=sales:5001
      - SHIPPING_SIGNALR=shipping:5003
  billing:
    build:
      context: ./
      dockerfile: ./Billing/Dockerfile
    container_name: billing
    ports:
      - "5002:80"
    environment:
      - LISTENING_PORT=80
      - ORIGIN_URL=http://frontend:8080
      - TRANSPORT_TYPE
      - CONNECTION_STRING
  shipping:
    build:
      context: ./
      dockerfile: ./Shipping/Dockerfile
    container_name: shipping
    ports:
      - "5003:80"
    environment:
      - LISTENING_PORT=80
      - ORIGIN_URL=http://frontend:8080
      - TRANSPORT_TYPE
      - CONNECTION_STRING
  sales:
    build:
      context: ./
      dockerfile: ./Sales/Dockerfile
    container_name: sales
    ports:
      - "5001:80"
    environment:
      - LISTENING_PORT=80
      - ORIGIN_URL=http://frontend:8080
      - TRANSPORT_TYPE
      - CONNECTION_STRING
  clientui:
    build:
      context: ./
      dockerfile: ./ClientUI/Dockerfile
    container_name: clientui
    ports:
      - "5000:80"
    environment:
      - LISTENING_PORT=80
      - ORIGIN_URL=http://frontend:8080
      - TRANSPORT_TYPE
      - CONNECTION_STRING

volumes:
  sc-data:
