services:
  service-control-db:
    container_name: servicecontrol-db
    image: particular/servicecontrol-ravendb:latest
    volumes:
      - sc-data:/var/lib/ravendb/data
  service-control:
    depends_on:
      service-control-db:
        condition: service_healthy
    container_name: servicecontrol
    image: particular/servicecontrol:latest
    command: "--setup-and-run"
    ports:
      - 33333:33333
    environment:
      - TRANSPORTTYPE
      - CONNECTIONSTRING=${CONNECTION_STRING}
      - RAVENDB_CONNECTIONSTRING=http://servicecontrol-db:8080
      - ALLOWMESSAGEEDITING=true
      - SHOW_PENDING_RETRY=true
  masstransit-connector:
    depends_on:
      service-control:
        condition: service_healthy
    container_name: masstransit-connector
    image:  particular/servicecontrol-connector-masstransit:0.1.0-alpha.4
    volumes:
      - ./queues.txt:/app/queues.txt:ro
    environment:
      - TRANSPORT_TYPE
      - CONNECTION_STRING
  service-pulse:
    depends_on:
      service-control:
        condition: service_healthy
    container_name: servicepulse
    image: particular/servicepulse:latest
    ports:
        - 9090:9090
    environment:
        SERVICECONTROL_URL: http://localhost:33333/api/
        ENABLE_REVERSE_PROXY: false
        SHOW_PENDING_RETRY: false
  vue-app:
    container_name: ui-app
    build:
      context: ./frontend  # Path to the folder containing Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    depends_on:
      - billing
    volumes:
      - ./frontend:/app  # Optional for hot reloading
    restart: always
  billing:
    build:
      context: ./
      dockerfile: ./src/Billing/Dockerfile
    container_name: billing 
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002  
  shipping:
    build:
      context: ./
      dockerfile: ./src/Shipping/Dockerfile
    container_name: shipping 
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:5003  
  sales:
    build:
      context: ./
      dockerfile: ./src/Sales/Dockerfile
    container_name: sales 
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001  
  clientui:
    build:
      context: ./
      dockerfile: ./src/ClientUI/Dockerfile
    container_name: clientui 
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000  
volumes:
  sc-data:
