name: servicecontrol-masstransit-demo
x-transport: &transport-env
  env_file: "rabbit.env"
   
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  service-control-db:
    container_name: "servicecontrol-db"
    image: "particular/servicecontrol-ravendb:latest"
    volumes:
      - sc-data:/opt/RavenDB/Server/RavenData
  service-control:
    depends_on:
      service-control-db:
        condition: service_healthy
    container_name: "servicecontrol"
    image: "particular/servicecontrol:latest"
    command: "--setup-and-run"
    << : [*transport-env]
  masstransit-connector:
    depends_on:
      - service-control
      - rabbitmq
    container_name: "masstransit-connector"
    image: "particular/servicecontrol-connector-masstransit:latest"
    command: "--setup-and-run"
    pull_policy: if_not_present
    << : [*transport-env]
  service-pulse:
    depends_on:
      - service-control
    container_name: "servicepulse"
    image: "particular/servicepulse:latest"
    ports:
        - 9090:9090
    environment:
        - SERVICECONTROL_URL=http://servicecontrol:33333/api/

volumes:
  sc-data:
  rabbitmq-data:
  rabbitmq-logs:
